### ISSUE TITLE
Function that do not return values should not be mandatory

### ISSUE THREAD

**Issue by elefevre** [matryer/moq#36]
I'm interested in making mocks more lenient (in the style of Mockito). That is, when a function does not return any value, then it should probably not be mandatory.
In other words, the mock should not panic when called on a function that is nil, as long as it does not return any value.

Thoughts?

**Comment by matryer** [comment]
I'd rather it was consistent. Especially as it's just a case of providing a function stub to jump panics. And I'd ask why calls to that function aren't being considered in the test if the dependency is worth mocking.

**Comment by elefevre** [comment]
This is your choice, of course. Although I do wish there was an alternative mock tool that was lenient on that aspect (I don't think there is).

Those interested in this topic might like to read more about lenient vs strict mocking framework, such as the corresponding paragraph in [this page](http://spockframework.org/spock/docs/1.0/interaction_based_testing.html).

**Comment by kaedys** [comment]
Realistically, I think it's at least as reasonable to add a `-stub` flag to the generator that simply removes the panic-if-unset semantic for that interface's mock.  There are a number of cases where I'm using mocks where I only set the behavior of a function when I actually need the behavior.  In many cases, if I'm testing later parts of the function, earlier calls to the function returning the zero values for the returns is perfectly viable.  Since I'm actually testing the calls to that function in other tests, ones that don't depend on that functions behavior, but _do_ still call it can use a trivial zero-value return for it.  

This is particularly the case for functions that return only an `error`, as returning a nil error is a convenient base case for mocked functions unless I specifically want other behavior, and having to define a trivial nil-returning function for every single such field in my BeforeEach is a bit of a pain.  A flag makes it a optional (and non-default) behavior, so the semantics of the library don't change for current users, but for those that _do_ want the trivial return (rather than panic) behavior can get it without hand-coding or lots of trivial function boilerplates.

**Comment by sudo-suhas** [comment]
Moq now supports a [`-stub` flag](https://github.com/matryer/moq#usage) to support this use-case. Example of generated code when flag is specified:
https://github.com/matryer/moq/blob/83ab8dd79f4cd81ed605de6b758d595889103053/pkg/moq/testpackages/channels/queuer_moq.golden.go#L57-L74
